import { v4 as uuid } from 'uuid';

export const customers = [
  {
    id: uuid(),
    address: {
      country: "INDIA",
      state: "Karnataka",
      city: "Benagaluru",
      street: "Kadernhalii Park, Banshankari Stage II",
    },
    avatarUrl: "/static/images/avatars/avatar_3.png",
    createdAt: 1555016400000,
    email: "rahul.ks@techieaid.in",
    name: "Rahul K.S",
    phone: "304-428-3097",
  },
  {
    id: uuid(),
    address: {
      country: "INDIA",
      state: "Karnataka",
      city: "Benagaluru",
      street: "Kadernhalii Park, Banshankari Stage II",
    },
    avatarUrl: "/static/images/avatars/avatar_4.png",
    createdAt: 1555016400000,
    email: "suresh@techieaid.in",
    name: "Suresh M",
    phone: "712-351-5711",
  },
  {
    id: uuid(),
    address: {
      country: "INDIA",
      state: "Karnataka",
      city: "Benagaluru",
      street: "Kadernhalii Park, Banshankari Stage II",
    },
    avatarUrl: "/static/images/avatars/avatar_2.png",
    createdAt: 1555016400000,
    email: "sunil@techieaid.in",
    name: "Sunil S",
    phone: "770-635-2682",
  },
  {
    id: uuid(),
    address: {
      country: "INDIA",
      state: "Karnataka",
      city: "Benagaluru",
      street: "Kadernhalii Park, Banshankari Stage II",
    },
    avatarUrl: "/static/images/avatars/avatar_5.png",
    createdAt: 1554930000000,
    email: "gaggan@techieaid.in",
    name: "Gagan Hebber",
    phone: "908-691-3242",
  },
  {
    id: uuid(),
    address: {
      country: "INDIA",
      state: "Karnataka",
      city: "Benagaluru",
      street: "Kadernhalii Park, Banshankari Stage II",
    },
    avatarUrl: "/static/images/avatars/avatar_6.png",
    createdAt: 1554757200000,
    email: "raj@techieaid.in",
    name: "Raj Kumar",
    phone: "972-333-4106",
  },
  {
    id: uuid(),
    address: {
      country: "INDIA",
      state: "Karnataka",
      city: "Benagaluru",
      street: "Kadernhalii Park, Banshankari Stage II",
    },
    avatarUrl: "/static/images/avatars/avatar_1.png",
    createdAt: 1554670800000,
    email: "fouder@techieaid.in",
    name: "Kiran Gopal Krishnan",
    phone: "858-602-3409",
  },
  {
    id: uuid(),
    address: {
      country: "INDIA",
      state: "Karnataka",
      city: "Benagaluru",
      street: "Kadernhalii Park, Banshankari Stage II",
    },
    avatarUrl: "/static/images/avatars/avatar_7.png",
    createdAt: 1554325200000,
    email: "co-founder@techieaid.in",
    name: "Sudhir Gurjaar",
    phone: "415-907-2647",
  },
  {
    id: uuid(),
    address: {
      country: "INDIA",
      state: "Karnataka",
      city: "Benagaluru",
      street: "Kadernhalii Park, Banshankari Stage II",
    },
    avatarUrl: "/static/images/avatars/avatar_8.png",
    createdAt: 1523048400000,
    email: "emilee.simchenko@devias.io",
    name: "Emilee Simchenko",
    phone: "702-661-1654",
  },
  {
    id: uuid(),
    address: {
      country: "INDIA",
      state: "Karnataka",
      city: "Benagaluru",
      street: "Kadernhalii Park, Banshankari Stage II",
    },
    avatarUrl: "/static/images/avatars/avatar_9.png",
    createdAt: 1554702800000,
    email: "kwak.seong.min@devias.io",
    name: "Kwak Seong-Min",
    phone: "313-812-8947",
  },
  {
    id: uuid(),
    address: {
      country: "INDIA",
      state: "Karnataka",
      city: "Benagaluru",
      street: "Kadernhalii Park, Banshankari Stage II",
    },
    avatarUrl: "/static/images/avatars/avatar_10.png",
    createdAt: 1522702800000,
    email: "merrile.burgett@devias.io",
    name: "Merrile Burgett",
    phone: "801-301-7894",
  },
];
